project_id = "auunqllzllvmqxrcmgss"

[functions.createCheckoutSession]
verify_jwt = false

[functions.stripeWebhook]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.verify-checkout-session]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false